### ISSUE TITLE
Support using a PCS PulseWorx UPB Gateway

### ISSUE THREAD

**Issue by dkelson** [gwww/upb-lib#12]
I have a PCS PulseWorx UPB Gateway that works well. Can upb-lib be updated to support the gateway to manage the upb devices/links?

They provide some integration notes here:

[PWX 128: PulseWorx Gateway Applications](https://cdn.shopify.com/s/files/1/0152/7169/0340/files/PWX_128_Pulseworx_Gateway_Apps.pdf)

And a full Gateway Development Kit that is available by request from PCS technical support.

**Comment by gwww** [comment]
I would be happy to accept a pull request with the changes. I don't have the time or desire to improve this integration much further at this time. If you (or someone else) decides to add this functionality I would prefer a few smaller PRs that incrementally add code so that it can be reviewed and tested easier.
